const projects = [
  {
    id: 1,
    title: "Accordion Component",
    description:
      "A simple and customizable accordion component built with React. Easily expand and collapse sections to display content.",
    path: "project/accordion",
  },
  {
    id: 2,
    title: "Sample",
    description: "This is a sample project description.",
    path: "project/sample",
  },
  {
    id: 3,
    title: "Sample",
    description: "This is a sample project description.",
    path: "project/sample",
  },
  {
    id: 4,
    title: "Sample",
    description: "This is a sample project description.",
    path: "project/sample",
  },
  {
    id: 5,
    title: "Sample",
    description: "This is a sample project description.",
    path: "project/sample",
  },
  {
    id: 6,
    title: "Sample",
    description: "This is a sample project description.",
    path: "project/sample",
  },
  {
    id: 7,
    title: "Sample",
    description: "This is a sample project description.",
    path: "project/sample",
  },
  {
    id: 8,
    title: "Sample",
    description: "This is a sample project description.",
    path: "project/sample",
  },
  {
    id: 9,
    title: "Sample",
    description: "This is a sample project description.",
    path: "project/sample",
  },
  {
    id: 10,
    title: "Sample",
    description: "This is a sample project description.",
    path: "project/sample",
  },
  {
    id: 11,
    title: "Sample",
    description: "This is a sample project description.",
    path: "project/sample",
  },
  {
    id: 12,
    title: "Sample",
    description: "This is a sample project description.",
    path: "project/sample",
  },
  {
    id: 13,
    title: "Sample",
    description: "This is a sample project description.",
    path: "project/sample",
  },
  {
    id: 14,
    title: "Sample",
    description: "This is a sample project description.",
    path: "project/sample",
  },
  {
    id: 15,
    title: "Sample",
    description: "This is a sample project description.",
    path: "project/sample",
  },
  {
    id: 16,
    title: "Sample",
    description: "This is a sample project description.",
    path: "project/sample",
  },
  {
    id: 17,
    title: "Sample",
    description: "This is a sample project description.",
    path: "project/sample",
  },
  {
    id: 18,
    title: "Sample",
    description: "This is a sample project description.",
    path: "project/sample",
  },
  {
    id: 19,
    title: "Sample",
    description: "This is a sample project description.",
    path: "project/sample",
  },
  {
    id: 20,
    title: "Sample",
    description: "This is a sample project description.",
    path: "project/sample",
  },
  {
    id: 21,
    title: "Sample",
    description: "This is a sample project description.",
    path: "project/sample",
  },
  {
    id: 22,
    title: "Sample",
    description: "This is a sample project description.",
    path: "project/sample",
  },
  {
    id: 23,
    title: "Sample",
    description: "This is a sample project description.",
    path: "project/sample",
  },
  {
    id: 24,
    title: "Sample",
    description: "This is a sample project description.",
    path: "project/sample",
  },
  {
    id: 25,
    title: "Sample",
    description: "This is a sample project description.",
    path: "project/sample",
  },
];
export default projects;
