const projects = [
  {
    id: 1,
    title: "Accordion Component",
    description:
      "A simple and customizable accordion component built with React. Easily expand and collapse sections to display content.",
    path: "project/accordion",
  },
  {
    id: 2,
    title: "Random Color Generator",
    description: "Generate random colors instantly with a single click. Copy color codes easily and explore endless color combinations.",
    path: "project/random-color-generator",
  },
  {
    id: 3,
    title: "Image Slider",
    description: "A clean and responsive image slider that lets you navigate through images smoothly with intuitive controls.",
    path: "project/image-slider",
  },
  {
    id: 4,
    title: "Load More Component ",
    description: "A dynamic content loading component that reveals additional items on demand. It improves performance by loading data in small batches and enhances user experience with smooth loading states and seamless pagination.",
    path: "project/load-more",
  },
  {
    id: 5,
    title: "Sample",
    description: "This is a sample project description.",
    path: "project/sample",
  },
  {
    id: 6,
    title: "Sample",
    description: "This is a sample project description.",
    path: "project/sample",
  },
  {
    id: 7,
    title: "Sample",
    description: "This is a sample project description.",
    path: "project/sample",
  },
  {
    id: 8,
    title: "Sample",
    description: "This is a sample project description.",
    path: "project/sample",
  },
  {
    id: 9,
    title: "Sample",
    description: "This is a sample project description.",
    path: "project/sample",
  },
  {
    id: 10,
    title: "Sample",
    description: "This is a sample project description.",
    path: "project/sample",
  },
  {
    id: 11,
    title: "Sample",
    description: "This is a sample project description.",
    path: "project/sample",
  },
  {
    id: 12,
    title: "Sample",
    description: "This is a sample project description.",
    path: "project/sample",
  },
  {
    id: 13,
    title: "Sample",
    description: "This is a sample project description.",
    path: "project/sample",
  },
  {
    id: 14,
    title: "Sample",
    description: "This is a sample project description.",
    path: "project/sample",
  },
  {
    id: 15,
    title: "Sample",
    description: "This is a sample project description.",
    path: "project/sample",
  },
  {
    id: 16,
    title: "Sample",
    description: "This is a sample project description.",
    path: "project/sample",
  },
  {
    id: 17,
    title: "Sample",
    description: "This is a sample project description.",
    path: "project/sample",
  },
  {
    id: 18,
    title: "Sample",
    description: "This is a sample project description.",
    path: "project/sample",
  },
  {
    id: 19,
    title: "Sample",
    description: "This is a sample project description.",
    path: "project/sample",
  },
  {
    id: 20,
    title: "Sample",
    description: "This is a sample project description.",
    path: "project/sample",
  },
  {
    id: 21,
    title: "Sample",
    description: "This is a sample project description.",
    path: "project/sample",
  },
  {
    id: 22,
    title: "Sample",
    description: "This is a sample project description.",
    path: "project/sample",
  },
  {
    id: 23,
    title: "Sample",
    description: "This is a sample project description.",
    path: "project/sample",
  },
  {
    id: 24,
    title: "Sample",
    description: "This is a sample project description.",
    path: "project/sample",
  },
  {
    id: 25,
    title: "Sample",
    description: "This is a sample project description.",
    path: "project/sample",
  },
];
export default projects;
